config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from .settings import settings
from coup.user_auth.views import LoginRedirectView, LogoutRedirectView


urlpatterns = [
    url(r'^conversations/', include('coup.conversations.urls', namespace='conversations')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('coup.dashboard.urls', namespace='dashboard')),
    url(r'^search/', include('coup.search.urls', namespace='search')),
    url(r'^positions/', include('coup.positions.urls', namespace='positions')),
    url(r'^users/', include ('coup.users.urls')),

    url(r'^user_auth/', include('coup.user_auth.urls')),
    # python-social-auth
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),

    # login redirects
    url(r'^login/$', LoginRedirectView.as_view(), name='login-redirect'),
    url(r'^log-in/$', LoginRedirectView.as_view(), name='login-redirect'),

    # logout redirects
    url(r'^logout/$', LogoutRedirectView.as_view(), name='logout-redirect'),
    url(r'^log-out/$', LogoutRedirectView.as_view(), name='logout-redirect'),

] +\
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coup/conversations/urls.py
from django.conf.urls import url
from .views import GroupList, GroupDetail, GroupCreate, GroupUpdate,\
    GroupDelete, ConversationList, ConversationDetail, ConversationCreate,\
    ConversationUpdate, ConversationDelete, MessageCreate, ConversationInitial,\
    GroupListAjax, ConversationListAjax, MessageListAjax, MessageCreateAjax

urlpatterns = [
    url(r'^groups/$', GroupList.as_view(), name='group-list'),
    url(r'^groups/create/$', GroupCreate.as_view(), name='group-create'),
    url(r'^groups/(?P<pk>\d+)/$', GroupDetail.as_view(), name='group-detail'),
    url(r'^groups/(?P<pk>\d+)/update/$', GroupUpdate.as_view(), name='group-update'),
    url(r'^groups/(?P<pk>\d+)/delete/$', GroupDelete.as_view(), name='group-delete'),
    url(r'^$', ConversationInitial.as_view(), name='conversation-initial'),
    url(r'^list/$', ConversationList.as_view(), name='conversation-list'),
    url(r'^create/$', ConversationCreate.as_view(), name='conversation-create'),
    url(r'^(?P<pk>\d+)/$', ConversationDetail.as_view(), name='conversation-detail'),
    url(r'^(?P<pk>\d+)/update/$', ConversationUpdate.as_view(), name='conversation-update'),
    url(r'^(?P<pk>\d+)/delete/$', ConversationDelete.as_view(), name='conversation-delete'),
    url(r'^(?P<pk>\d+)/create/$', MessageCreate.as_view(), name='message-create'),
    url(r'^group-list-ajax/$', GroupListAjax, name='group-list-ajax'),
    url(r'^conversation-list-ajax/$', ConversationListAjax, name='conversation-list-ajax'),
    url(r'^message-list-ajax/$', MessageListAjax, name='message-list-ajax'),
    url(r'^message-create-ajax/$', MessageCreateAjax, name='message-create-ajax'),
]

coup/dashboard/urls.py
from django.conf.urls import url

from coup.positions.views import PositionOverview

urlpatterns = [
    url(
        regex = r'^$',\
        view = PositionOverview.as_view(),\
        name = 'DashBoardView'
    ),
]

coup/search/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from ..api import views as api

urlpatterns = [
    url(
        regex = r'^$',\
        view = views.SearchView.as_view(),\
        name = 'searchView'
    ),
    url(
        regex = r'^api/get_titles',\
        view = api.get_titles,\
        name = 'get_titles'
    ),
    url(
        regex = r'^api/get_companies',\
        view = api.get_companies,\
        name = 'get_companies'
    ),
    url(
        regex = r'^api/get_usernames',\
        view = api.get_usernames,\
        name = 'get_usernames'
    ),
    url(
        regex = r'^api/get_fullnames',\
        view = api.get_fullnames,\
        name = 'get_fullnames'
    ),
    url(r'^admin/', admin.site.urls),
]

coup/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
from coup.user_auth.views import LoginRedirectView, LogoutRedirectView

app_name = 'users'
urlpatterns = [
    url(
        r'^(?P<slug>[a-zA-Z0-9]+)/profile/$',\
        views.UserDetailView.as_view(),\
         name="view_profile"
    ),
    url(
        r'^(?P<slug>[a-zA-Z0-9]+)/profile/edit/$',\
        views.UserUpdateView.as_view(),\
         name="update_profile"
    ),
    url(
        r'^login/$',\
        LoginRedirectView.as_view(),\
        name='login-redirect'
    ),
    url(
        r'^log-in/$',\
        LoginRedirectView.as_view(),\
        name='login-redirect'
    ),
    url(
        r'^logout/$',\
        LogoutRedirectView.as_view(),\
        name='logout-redirect'
    ),
    url(
        r'^log-out/$',\
        LogoutRedirectView.as_view(),\
        name='logout-redirect'
    )    
    # url(r'^account_redirect/$', views.account_redirect, name='account-redirect')

]

coup/positions/forms.py
from django import forms
from .models import Position, Comment


class PositionForm(forms.ModelForm):
    """
    This form simplifies the creation of a view and template
    for the addition of positions to user profiles.
    """
    class Meta:
        model = Position
        fields = (
            'company',
            'title',
            'start_year',
            'end_year',
            'start_month',
            'end_month',
            'location_addr',
            'location_lat',
            'location_lng'
        )

class CommentForm(forms.ModelForm):
    """
    This forms simplifies the creation of a view and template
    for the addition of comments on positions held by a certain user.
    """
    class Meta:
        model = Comment
        fields = (
            'comment',
        )

coup/user_auth/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth.models import User
from ..users.models import User, getChoices

class SignUpForm (UserCreationForm):
    """
    This form extends from the basic UserCreationForm,
    which is responsible for USERNAME and PASSWORD fields.
    """
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'placeholder': 'User Name'}),required = True)
    email = forms.EmailField(label='E-mail Address', widget=forms.TextInput(attrs={'placeholder': 'E-mail Address'}),required = True)
    password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'placeholder': 'Password'}),required = True)
    password2 = forms.CharField(label='Confirm Password',widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}),required = True)

    class Meta:
        model = User
        # order of field appearance
        fields = [
            'username',
            'email',
            'password1',
            'password2',
        ]

coup/actions/views.py
from django.shortcuts import render

# Create your views here.

coup/api/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Q

from ..positions.models import Position
from ..users.models import User

import json


def get_generic_val(request,
                    cb_filter,
                    *args):
    """
    Generic API to be wrapped to 
    query specific database fields 
    based on user input.     
    """
    content_type = 'application/json'

    if request.is_ajax():
        term_s = request.GET['term'][0]
        object_l = cb_filter(term_s)
        delimeter = ' '

        match_l = []    
        dup_d = {}
        for obj in object_l:
            field_l = []  
            for field in args:
                field_l.append(\
                    obj.__dict__[field])
            match = delimeter.join(field_l)
            if match not in dup_d:
                match_l.append(\
                    match)
                dup_d[match] = 1
        
        data = json.dumps(match_l)

    else:
        data = 'fail'

    return HttpResponse(data,\
        content_type = content_type) 

def position_title_wrapper(title_s):
    """
    Wraps the Position.objects.filter
    method on title__icontains kwarg.
    """
    return Position.objects.filter(\
        title__icontains = title_s)

def position_company_wrapper(company_s):
    """
    Wraps the Position.objects.filter
    method on company__icontains kwarg.
    """
    return Position.objects.filter(\
        company__icontains = company_s)

def user_username_wrapper(username_s):
    """
    Wraps the User.objects.filter
    method on username__icontains kwarg.
    """
    return User.objects.filter(\
        username__icontains = username_s)

def user_fullname_wrapper(fullname_s):
    """
    Wraps the User.objects.filter
    method on first_name__icontains
    and last_name__icontains kwargs.
    """
    name_l = fullname_s.split(' ')
    try:
        return User.objects.filter(\
            first_name__icontains = name_l[0],\
            last_name__icontains = name_l[1])        

    except IndexError:        
        return User.objects.filter(\
            Q(first_name__icontains = name_l[0]) |\
            Q(last_name__icontains = name_l[0]))

def get_titles(request):
    """
    Queries for positions starting with input 
    contained within GET request.
    """
    return get_generic_val(request,\
        position_title_wrapper,\
        'title') 

def get_companies(request):
    """
    Queries for company names starting 
    with input contained within GET request.
    """
    return get_generic_val(request,\
        position_company_wrapper,\
        'company') 

def get_usernames(request):
    """
    Queries for usernames starting with input
    contained within GET request.
    """
    return get_generic_val(request,\
        user_username_wrapper,\
        'username')        

def get_fullnames(request):
    """
    Queries for first/last names starting with input
    contained within GET request.
    """
    return get_generic_val(request,\
        user_fullname_wrapper,\
        'first_name',
        'last_name')        

coup/core/views.py
from django.shortcuts import render

# Create your views here.

coup/dashboard/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

from coup.positions.models import Position, Comment
from coup.users.models import User

LOGIN_URL = '/login/'

def recommend_user(self):
        
    
    rec_users = user_objects.filter(Q(faculty="Sciences")\
                                             | Q(program="Computing Science"))
    return rec_users
    
class DashBoardView(LoginRequiredMixin,\
                    ListView):
    """
    Generic view used to render the homepage aka
    dashboard of the website.
    """
    login_url = LOGIN_URL
    model = User
    template_name = "dashboard/index.html"

    def get_context_data(self, **kwargs):
        context = super(DashBoardView, self).get_context_data(**kwargs)
        #context['recent_list'] = Position.objects.exclude(\
         #                           user=self.request.user).order_by('-id')
        
        """user_objects = User.objects.exclude(id=self.request.user.id)
        rec_users = user_objects.filter(\
                                Q(faculty=self.request.user.faculty) | \
                                Q(program=self.request.user.program))

        context['recommend_users'] = rec_users"""
        return context


    

coup/positions/views.py
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.shortcuts import render,\
                             redirect,\
                             get_object_or_404

from .forms import PositionForm, CommentForm
from .models import Position, Comment
from coup.users.models import User
# Create your views here.

LOGIN_URL = '/login/'


class PositionListView(LoginRequiredMixin,\
                           generic.ListView):
    """
    Lists the positions of the user which 
    is currently logged in
    """
    login_url = LOGIN_URL
    paginate_by = 2
    template_name = 'positions/position_overview.html'
    model = Position

    def get_queryset(self):
        return Position.objects.filter(user=self.request.user)
    

class PositionOverview(LoginRequiredMixin,\
                       generic.ListView):
    """
    Displays the dashboard of the app.
    """
    login_url = LOGIN_URL
    model = User
    template_name = 'positions/index.html'

    def get_context_data(self, **kwargs):
        context = super(PositionOverview, self).get_context_data(**kwargs)
        context['recommended_list'] = Position.objects.filter(\
            user__faculty=self.request.user.faculty).order_by('-id')[0:5]
        context['recent_list'] = Position.objects.exclude(\
                                    user=self.request.user).order_by('-id')[0:5]
        context['position_list'] = Position.objects.filter(user=self.request.user)
        return context


class PositionDetailView(LoginRequiredMixin,\
                         generic.DetailView):
    """
    Generic view to display details of a specific position.
    """
    login_url = LOGIN_URL
    model = Position


@login_required(login_url = LOGIN_URL)
def add_position(request):
    """
    view generates the template to add a new position
    and comment and awaits a POST request by the user.
    """
    if request.method == "POST":
        form1 = PositionForm(request.POST)
        form2 = CommentForm(request.POST)
        if (form1.is_valid() & form2.is_valid()):
            position = form1.save(commit=False)
            if position.location_addr is not None:
                if position.company in position.location_addr:
                    new_addr = position.location_addr.split(',')[1:]
                    position.location_addr = ','.join(new_addr)
            position.user = request.user
            position.generate_slug()
            position.save()
            comment = form2.save(commit=False)
            comment.position = position
            comment.user = request.user
            comment.save()
            return redirect('positions:position-detail',\
                pk=position.pk,\
                slug=position.slug) 
    else:
        form1 = PositionForm()
        form2 = CommentForm()
    return render(request, 'positions/position_add.html',{'form1':form1, 'form2':form2})


@login_required(login_url = LOGIN_URL)
def edit_position(request, *args, **kwargs):
    """
    Enables the user to edit a position added to the DB
    in case an error was recorded.
    """
    pk = kwargs['pk'][0]
    position = get_object_or_404(Position, pk=pk)
    comment = Comment.objects.get(position=pk)
    
    if request.user != position.user:
        return HttpResponseRedirect('/user_auth/error')

    if request.method == "POST":
        form1 = PositionForm(request.POST, instance=position)
        form2 = CommentForm(request.POST, instance=comment)
        if (form1.is_valid() & form2.is_valid()):
            position = form1.save(commit=False)
            if position.company in position.location_addr:
                new_addr = position.location_addr.split(',')[1:]
                position.location_addr = ','.join(new_addr)
            position.save()
            comment = form2.save(commit=False)
            comment.save()
            return redirect('positions:position-detail',\
                pk=position.pk,\
                slug=position.slug)
    else:
        form1 = PositionForm(instance=position)
        form2 = CommentForm(instance=comment)
    return render(request, 'positions/position_edit.html', {'form1':form1, 'form2':form2})


@login_required(login_url = LOGIN_URL)
def delete_position(request, *args, **kwargs):
    """
    Enables the user to delete a position they have posted to
    the database
    """
    position = get_object_or_404(Position, **kwargs).delete()
    return redirect('positions:index') 

coup/search/views.py
from django.views.generic import ListView
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserSearchForm, PositionSearchForm
from ..positions.models import Position, Comment
from ..users.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


LOGIN_URL = '/login/'

class SearchView(LoginRequiredMixin,\
                 ListView):
    """
    View to display search form for users / interview questions
    of specific positions.
    """
    login_url = LOGIN_URL
    model = Position 
    template_name = 'search/search.html'
    paginate_by = 2

    POSITION_KEY = 'company'
    USER_KEY = 'username'

    def get_context_data(self,\
                         *args,\
                         **kwargs):
        """
        Gets all relevant data for template context.
        """
        data = super(SearchView, self).\
            get_context_data(**self.request.GET)
        data['positions_form'] = PositionSearchForm
        data['users_form'] = UserSearchForm
        return data
        
    def get_queryset(self,
                     **kwargs):
        """
        Performs filtering of positions based on GET parameters.
        """
        if self.POSITION_KEY in self.request.GET:
            positions_l = Position.objects.\
                query_on_params(**self.request.GET)
            return positions_l

        elif self.USER_KEY in self.request.GET:
            users_l = User.objects.\
                query_on_params(**self.request.GET)
            return users_l

        else:
            return []
    

coup/templates/conversations/conversation_detail.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}
{% block extra-head %}
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations_form.css' %}">
{% endblock %}

    <h2 id="profile-header">
        {{ conversation.group.name }}
    </h2>
    <a class="profile-link header-link"
        href="{% url 'conversations:conversation-list' %}">
        Back To Conversations
    </a>

    <div class="description">
        <ul class="description-details">
            <li class="detail">
                <label>
                    Subject:
                </label>
                {{ conversation.subject }}
            </li>
            
            <li class="detail">
                <label>
                    History:
                </label>
                <ul>
                    {% for message in conversation_messages %}
                        <li>
                            <p>{{ message.user }}: {{ message.created }}</p>
                            </p>{{ message.text }}</p>
                        </li>
                </ul>
                {% empty %}
                    No messages to show
            {% endfor %}
            <li class="detail">  
                <a href="{% url 'conversations:conversation-update' conversation.pk %}"
                    class="profile-link"
                    id="update-position">
                    Edit Conversation
                </a>
                <a href="{% url 'conversations:conversation-delete' conversation.pk %}"
                    class="profile-link">
                    Delete Conversation
                </a>
            </li>
        </ul>
    </div>

{% endblock %}

coup/templates/conversations/conversation_form.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}
{% block extra-head %}
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations_form.css' %}">
{% endblock %}
<form action="" method="post">
    {%  csrf_token %}
    
    
    <table>
        {% if form.group %}
        <tr class="group-input">
            <th class="group-header">Group : </th>
                <td>{{ form.group }}</td>
        </tr>
        {% endif %}
        <tr class="subject-input">
            <th class="subject-header">Subject : </th>
            <td>{{ form.subject }}</td>
    </table>
    <button type="submit" value="Submit">Submit</button>
    
 </form>
 {% endblock %}

coup/templates/conversations/conversation_list.html
{% extends "base_generic.html" %}
{% load static %}
{% block extra-head %}
    <script 
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations.css' %}"
    >
{% endblock %}
{% block content %}
   <label>Conversations</label>
    <div class="conversations-list">
        {% for conversation in conversation_list %}
            <a href="{% url 'conversations:conversation-detail' conversation.pk %}" class="conversation-link"> 
                    <button class="list">
                        {{ conversation.subject }} 
                    </button>
                </a>
        
        {% empty %}
            <p>No conversations to show</p>
        {% endfor %}
    </div>
    <br>
    <a href="{% url 'conversations:conversation-create' %}"><button>New Conversation</button> </a>
{% endblock %}

coup/templates/conversations/conversation_list_ajax.html
{% block content %}
    <div class="conversations-block">
        <ul class="conversations-list" data-url="{% url 'conversations:message-list-ajax' %}">
        {% for conversation in conversations_list %}
        <li>
            <a href="#" class="conversation-link">
                <button class="conversation-name" data-id="{{conversation.pk}}"> {{ conversation.subject }} </button>
            </a>
        </li>
        {% empty %}
            <p class="stop">No conversations to show</p>
        {% endfor %}
        </ul>
{% endblock %}

coup/templates/conversations/conversations.html
{% extends "base_generic.html" %}
{% load static %}
{% block extra-head %}
    <script 
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations.css' %}">
    <script 
        src="{% static 'javascript/conversations.js' %}">
    </script>    
{% endblock %}
{% block content %}
    <div class="wrapper">
        <h2>Messaging Overview</h2>
        <div class="description">
        <div class="left">
            <label>Groups</label>
            <button class="up-group" data-group-url="{% url 'conversations:group-list-ajax' %}">&#9650;</button>
            <ul class="groups-list" data-url="{% url 'conversations:conversation-list-ajax' %}">
                {% for group in groups_list %}
                    <li>
                    <a href="#" class="group-link">
                        <button class="group-name" data-id="{{group.pk}}">{{ group.name }}</button>
                    </a>
                    </li>
        
                {% empty %}
                    <p>No groups to show</p>
                {% endfor %}
            </ul>
            <button class="down-group" data-group-url="{% url 'conversations:group-list-ajax' %}">&#9660;</button>
            <br>
            <a class="message-link"
                href="{% url 'conversations:group-create' %}">
                New Group
            </a>
            <a class="message-link"
                href="{% url 'conversations:group-list' %}">
                Edit Groups
            </a>
            <br><br>
            <label>Conversations</label>
            <button class="up-conv" data-conv-url="{% url 'conversations:conversation-list-ajax' %}">&#9650;</button>
            <div class="conversations-block">
                <ul class="conversations-list" data-url="{% url 'conversations:message-list-ajax' %}">
                    {% for conversation in conversations_list %}
                        <li>
                        <a href="#" class="conversation-link">
                            <button class="conversation-name" data-id="{{conversation.pk}}">{{ conversation.subject }}</button>
                        </a>
                        </li>
                    {% empty %}
                        <p>No conversations to show</p>
                    {% endfor %}
                </ul>
            </div>
            <button class="down-conv" data-conv-url="{% url 'conversations:conversation-list-ajax' %}">&#9660;</button>
            <br>
            <a class="message-link"
                href="{% url 'conversations:conversation-create' %}">
                New Conversation
            </a>
            <a class="message-link"
                href="{% url 'conversations:conversation-list' %}">
                Edit Conversations
            </a>
        </div>
    
        <div class="right">
            <label>Messages</label>
            <div class="messages-block"> 
                <ul class="messages-list">
                    <li> Click on a group and a message </li>            
                </ul>
        
            </div>
            <br>
            <textarea name="message-box" class="msg-box" data-msg="{% url 'conversations:message-create-ajax' %}"></textarea>
            <button type="submit" value="submit" class="btn-send">Send</button>
        </div>
        </div>
    </div>
    <br><br><br><br><br><br><br><br><br><br>

    
{% endblock %}

coup/templates/conversations/delete_confirm.html
{% block content %}
{% load static %}
{% block extra-head %}
    <script 
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations_form.css' %}"
    >
{% endblock %}
    <form action="" method="post">{% csrf_token %}
        <div class="delete-confirmation">
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <button type="submit" class="confirm">Confirm </button>
        </div>
    </form>
{% endblock %}

coup/templates/conversations/group_detail.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}
{% block extra-head %}
    <script 
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations.css' %}"
    >
{% endblock %}
    <h2 id="profile-header">
        {{ group.name }}
    </h2>
    <a class="profile-link header-link"
        href="{% url 'conversations:group-list' %}">
        Back to Groups
    </a>
    <a class="profile-link header-link"
        href="{% url 'conversations:conversation-create' %}">
        Start a Conversation
    </a>
    
    <div class="description">
        <ul class="description-details">
            <li class="detail">
                <label>
                    Subject:
                </label>
                {{ group.subject }}
            </li>
            <li class="detail">
                <label>
                    Description:
                </label>
                {{ group.description }}
            </li>
            <li class="detail">
                <label>
                    Users:
                </label>
                {% for user in group.users.all %}
                    <div>
                        {{ user.username }}
                    </div>
                {% empty %}
                    <p>No users to show</p>
                {% endfor %}
            </li>
            <br>
            <li class="detail">
                <a href="{% url 'conversations:group-update' group.pk %}"
                    class="profile-link"
                    id="update-position">
                    Edit Group 
                </a>
                <a href="{% url 'conversations:group-delete' group.pk %}"
                    class="profile-link">
                    Delete Group
                </a>
            </li>
        </ul>
    </div>
{% endblock %}

coup/templates/conversations/group_form.html
{% extends "base_generic.html" %}
{% load static %}
{% block extra-head %}
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations_form.css' %}">
{% endblock %}
{% block content %}
<form action="" method="post">
    {%  csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <!--<div class="group-form-name">
    <label for="{{ form.name.id_for_label }}"> Group name </label>
        {{ form.name }}
    </div>
    <div class="group-form-subject">
    <label for="{{ form.name.id_for_label }}"> Subject </label>
        {{ form.subject }}
    </div>
    <div class="group-form-description">
    <label for="{{ form.name.id_for_label }}"> Description </label>
        {{ form.description }}
    </div>
    <div class="group-form-locked">
    <label for="{{ form.name.id_for_label }}"> Locked </label>
        {{ form.locked }}
    </div>
    <div class="group-form-users">
    <label for="{{ form.name.id_for_label }}"> Users </label>
        {{ form.users }}
    </div>-->
    <Button type="submit" value="Submit">Submit</button>
    
</form>
{% endblock %}

coup/templates/conversations/group_list.html
{% extends "base_generic.html" %}
{% block content %}
{% load static %}
{% block extra-head %}
    <script 
        src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    </script>
    <link 
        rel="stylesheet" 
        href="{% static 'css/conversations.css' %}"
    >
{% endblock %}
    <h1>Groups</h1>
    <ul>
    {% for group in group_list %}
        <li>
            <a href="{% url 'conversations:group-detail' group.pk %}" class="group-link">
            <button class="list">
                {{ group.name }} : {{ group.subject }}
            </button>
            </a>
        </li>
    {% empty %}
        <p>No groups to show</p>
    {% endfor %}
    </ul>
    <br>
    <a href="{% url 'conversations:group-create' %}"> <button>New Group</a></button>
{% endblock %}

coup/templates/conversations/group_list_ajax.html
{% block content %}
    <ul class="groups-list" data-url="{% url 'conversations:conversation-list-ajax' %}">
        {% for group in groups_list %}
        <li>
            <a href="#" class="group-link">
                <button class="group-name" data-id="{{group.pk}}">{{ group.name }}</button>
            </a>
        </li>
        
        {% empty %}
            <p class="stop">No groups to show</p>
        {% endfor %}
    </ul>
{% endblock %}

coup/templates/conversations/message_form.html
{% block content %}
<h1>Message</h1>
<form action="" method="post">
    {%  csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    
</form>
{% endblock %}

coup/templates/conversations/message_list_ajax.html
{% block content %}
    <ul class="messages-list">
        {% for message in messages_list %}
            <li>{{ message.created }} {{ message.user.username }} : 
                <p>{{ message.text }}</p>
            </li>
        {% empty %}
            <p>No messages to show</p>
        {% endfor %}
    </ul>
{% endblock %}

coup/templates/conversations/test.html
{% block content %}

<p>POP POP MOFUCKA</p>
{% endblock %}