config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

from .settings import settings
from coup.user_auth.views import LoginRedirectView, LogoutRedirectView


urlpatterns = [
    url(r'^conversations/', include('coup.conversations.urls', namespace='conversations')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('coup.dashboard.urls', namespace='dashboard')),
    url(r'^search/', include('coup.search.urls', namespace='search')),
    url(r'^positions/', include('coup.positions.urls', namespace='positions')),
    url(r'^users/', include ('coup.users.urls')),

    url(r'^user_auth/', include('coup.user_auth.urls')),
    # python-social-auth
    url('social-auth/', include('social.apps.django_app.urls', namespace='social')),

    # login redirects
    url(r'^login/$', LoginRedirectView.as_view(), name='login-redirect'),
    url(r'^log-in/$', LoginRedirectView.as_view(), name='login-redirect'),

    # logout redirects
    url(r'^logout/$', LogoutRedirectView.as_view(), name='logout-redirect'),
    url(r'^log-out/$', LogoutRedirectView.as_view(), name='logout-redirect'),

] +\
static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coup/dashboard/urls.py
from django.conf.urls import url

from coup.positions.views import PositionOverview

urlpatterns = [
    url(
        regex = r'^$',\
        view = PositionOverview.as_view(),\
        name = 'DashBoardView'
    ),
]

coup/positions/urls.py
from django.conf.urls import url, include
from . import views


app_name = 'positions'
urlpatterns = [
    url(r'^overview/$', views.PositionListView.as_view(), name='index'),
    url(r'^add/$', views.add_position, name='add-position'),
    url(r'^(?P<pk>\d+)-(?P<slug>[-\w\d]+)/', include([
        url(r'^detail/$', views.PositionDetailView.as_view(), name='position-detail'),
        url(r'^edit/$', views.edit_position, name='edit-position'),
        url(r'^delete/$', views.delete_position, name='delete-position'),
    ])),
]

coup/search/urls.py
from django.conf.urls import url
from django.contrib import admin

from . import views
from ..api import views as api

urlpatterns = [
    url(
        regex = r'^$',\
        view = views.SearchView.as_view(),\
        name = 'searchView'
    ),
    url(
        regex = r'^api/get_titles',\
        view = api.get_titles,\
        name = 'get_titles'
    ),
    url(
        regex = r'^api/get_companies',\
        view = api.get_companies,\
        name = 'get_companies'
    ),
    url(
        regex = r'^api/get_usernames',\
        view = api.get_usernames,\
        name = 'get_usernames'
    ),
    url(
        regex = r'^api/get_fullnames',\
        view = api.get_fullnames,\
        name = 'get_fullnames'
    ),
    url(r'^admin/', admin.site.urls),
]

coup/users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views
from coup.user_auth.views import LoginRedirectView, LogoutRedirectView

app_name = 'users'
urlpatterns = [
    url(
        r'^(?P<slug>[a-zA-Z0-9]+)/profile/$',\
        views.UserDetailView.as_view(),\
         name="view_profile"
    ),
    url(
        r'^(?P<slug>[a-zA-Z0-9]+)/profile/edit/$',\
        views.UserUpdateView.as_view(),\
         name="update_profile"
    ),
    url(
        r'^login/$',\
        LoginRedirectView.as_view(),\
        name='login-redirect'
    ),
    url(
        r'^log-in/$',\
        LoginRedirectView.as_view(),\
        name='login-redirect'
    ),
    url(
        r'^logout/$',\
        LogoutRedirectView.as_view(),\
        name='logout-redirect'
    ),
    url(
        r'^log-out/$',\
        LogoutRedirectView.as_view(),\
        name='logout-redirect'
    )    
    # url(r'^account_redirect/$', views.account_redirect, name='account-redirect')

]

coup/api/models.py
from django.db import models

# Create your models here.

coup/positions/models.py
import datetime
import math

from django.db import models
from django.conf import settings
from django.urls import reverse

from coup.core.models import TimeStampedModel
from coup.users.models import User


class PositionManager(models.Manager):
    """
    Custom model manager extending over django's
    default model manager.
    """
    use_for_related_fields = True
    
    DEFAULT_INPUT = ''

    def query_on_params(self,\
                        **kwargs):
        """
        Method called by search view to filter on:
            - title
            - company
            - start/end year/month
        """
        # check for empty query
        if self.check_empty_query(**kwargs):
            return []

        return self.filter_positions(**kwargs)

    def quick_query(self,\
                    value):
        """
        Handles quick queries based on
        a single value.
        """
        # first filter on required fields
        return self.all().filter(\
            company__icontains = value)


    def filter_positions(self,\
                         **kwargs):
        """
        Handles direct queries on:
            - company
            - title
            - start/end year
            - start/end month
            - location within km radius 
        """
        # search filters
        company_s = kwargs['company'][0]
        title_s = kwargs['title'][0]
        start_year = kwargs['start_year'][0]
        start_month = kwargs['start_month'][0]
        end_year = kwargs['end_year'][0]
        end_month = kwargs['end_month'][0]
        location_lat = kwargs['location_lat'][0]
        location_lng = kwargs['location_lng'][0]

        # start with all objects
        query_set = self.all()
        # first filter on required fields
        if company_s == '' and title_s == '':
            pass
        elif title_s == '':
            query_set = query_set.filter(\
                company__icontains = company_s)
        elif company_s == '':
            query_set = query_set.filter(\
                title__icontains = title_s)
        else:
            query_set = query_set.filter(\
                company__icontains = company_s,\
                title__icontains = title_s)

        # second filter on date fields
        if start_year != self.DEFAULT_INPUT:
            query_set = query_set.filter(\
                start_year__gte = start_year)
        if end_year != self.DEFAULT_INPUT:
            query_set = query_set.filter(\
                end_year__lte = end_year)
        if start_month != self.DEFAULT_INPUT:
            query_set = query_set.filter(\
                start_month__gte = start_month)
        if end_month != self.DEFAULT_INPUT:
            query_set = query_set.filter(\
                end_month__lte = end_month)

        # filter on location 
        if location_lat != self.DEFAULT_INPUT and\
           location_lng != self.DEFAULT_INPUT:
            query_set = self.get_nearby_positions(\
                query_set,\
                float(location_lat),\
                float(location_lng))
  
        return query_set

    def get_nearby_positions(self,\
                             query_set,\
                             curr_lat,\
                             curr_lng):
        """
        Returns all positions in the query set
        within a 10km box of the given 
        latitude/longitude coordinate.
        """
        distance = 10.0
        earth_radius = 6371.0;

        delta_lat = math.degrees(distance/earth_radius)
        max_lat = curr_lat + delta_lat
        min_lat = curr_lat - delta_lat

        radius_at_lng = earth_radius*math.cos(math.radians(curr_lat))
        delta_lng = math.degrees(distance/radius_at_lng)
        max_lng = curr_lng + delta_lat
        min_lng = curr_lng - delta_lat

        return query_set.filter(location_lat__gte = min_lat,\
            location_lat__lte = max_lat,\
            location_lng__gte = min_lng,\
            location_lng__lte = max_lng)
         
        
    def check_empty_query(self,\
                          **kwargs):
        """
        Returns True if passed query parameters
        are empty, False otherwise.
        """
        for value in kwargs.values():
            if value[0] != self.DEFAULT_INPUT:
                return False
        return True


class Position(models.Model):
    """
    Stores details about a specific co-op position.
    Shares a many-to-many relationship with the User model.
    TODO: GLASSDOOR API INTEGRATION FOR INTERVIEW QUESTIONS
    """
    # add custom manager
    objects = PositionManager()

    # choices for year
    YEAR_CHOICES = []
    for r in range(2000, (datetime.datetime.now().year+1)):
        YEAR_CHOICES.append((str(r),str(r)))

    # choices for month
    MONTH_CHOICES = []
    for i in range(1,13):
        month_s = datetime.date(i,i,i).strftime('%B')
        MONTH_CHOICES.append((month_s, month_s))

    # company name and job title
    company = models.CharField(max_length = 30)
    title = models.CharField(max_length = 30)

    # start year/month
    start_year = models.CharField(choices = YEAR_CHOICES,\
        max_length = 4,\
        default = YEAR_CHOICES[0][0])
    start_month = models.CharField(max_length = 9,\
        choices = MONTH_CHOICES,\
        default = MONTH_CHOICES[0][0])

    # end year/month
    end_year = models.CharField(choices = YEAR_CHOICES,\
        max_length = 4,\
        null = True,\
        blank = True)
    end_month = models.CharField(max_length = 9,\
        choices = MONTH_CHOICES,\
        null = True,\
        blank = True) 

    # location in terms of lat/lng coordinates
    location_lat = models.FloatField(max_length = 20,\
        null = True,\
        blank = True)
    location_lng = models.FloatField(max_length = 20,\
        null = True,\
        blank = True)    

    # location in terms of human readable address
    location_addr = models.CharField(max_length = 100,\
        null = True,\
        blank = True)

    # user who owns the position
    user = models.ForeignKey(User,\
        on_delete = models.CASCADE,\
        null = True)

    # slug for readable urls
    slug = models.SlugField()

    def __str__(self):
        return "%s %s" % (self.company, self.title)

    # Returns the url to access a particular position
    def get_absolute_url(self):
        return reverse('positions:position-detail', \
            kwargs={\
                'pk' : self.id, \
                'slug' : str(self.slug)
            }
        )

    def generate_slug(self):
        """
        Sets slug for position url
        as username-title-company.
        """ 
        new_slug = '{}-{}'.format(\
            '-'.join(self.title.lower().split(' ')),\
            '-'.join(self.company.lower().split(' ')))

        self.slug = new_slug
        return new_slug


class CommentManager(models.Manager):
    """
    Custom manager for Comment extending
    over django's default manager.
    """
    use_for_related_fields = True
    
    def query_on_position(self,\
                          positions_l):
        """
        Queries for users related to positions
        in positions_l.
        """
        users_l = []
        for _p in positions_l:
            related_l = self.filter(position = _p)
            for _r in related_l:
                users_l.append(_r.user)
        return users_l
    
    def query_on_user(self,\
                      users_l):
        """
        Queries for positions related to users
        in users_l.
        """
        positions_l = []
        for _u in users_l:
            related_l = self.filter(user = _u)
            for _r in related_l:
                positions_l.append(_r.position)
        return positions_l
    

class Comment(TimeStampedModel):
    """
    Model to store specific user comments about
    specific positions.
    Shares a foreign key relationship with:
        - User
    """
    # custom manager
    objects = CommentManager()

    comment = models.TextField(max_length=200,\
        null = True,\
        blank = True)
    position = models.ForeignKey(Position,\
        on_delete = models.CASCADE, \
        null = True)
    user = models.ForeignKey(User,\
        on_delete = models.CASCADE, \
        null = True)

    def __str__(self):
        return ' '.join([
            'comment',
            str(self.id),
        ])

coup/positions/forms.py
from django import forms
from .models import Position, Comment


class PositionForm(forms.ModelForm):
    """
    This form simplifies the creation of a view and template
    for the addition of positions to user profiles.
    """
    class Meta:
        model = Position
        fields = (
            'company',
            'title',
            'start_year',
            'end_year',
            'start_month',
            'end_month',
            'location_addr',
            'location_lat',
            'location_lng'
        )

class CommentForm(forms.ModelForm):
    """
    This forms simplifies the creation of a view and template
    for the addition of comments on positions held by a certain user.
    """
    class Meta:
        model = Comment
        fields = (
            'comment',
        )

coup/actions/views.py
from django.shortcuts import render

# Create your views here.

coup/api/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.db.models import Q

from ..positions.models import Position
from ..users.models import User

import json


def get_generic_val(request,
                    cb_filter,
                    *args):
    """
    Generic API to be wrapped to 
    query specific database fields 
    based on user input.     
    """
    content_type = 'application/json'

    if request.is_ajax():
        term_s = request.GET['term'][0]
        object_l = cb_filter(term_s)
        delimeter = ' '

        match_l = []    
        dup_d = {}
        for obj in object_l:
            field_l = []  
            for field in args:
                field_l.append(\
                    obj.__dict__[field])
            match = delimeter.join(field_l)
            if match not in dup_d:
                match_l.append(\
                    match)
                dup_d[match] = 1
        
        data = json.dumps(match_l)

    else:
        data = 'fail'

    return HttpResponse(data,\
        content_type = content_type) 

def position_title_wrapper(title_s):
    """
    Wraps the Position.objects.filter
    method on title__icontains kwarg.
    """
    return Position.objects.filter(\
        title__icontains = title_s)

def position_company_wrapper(company_s):
    """
    Wraps the Position.objects.filter
    method on company__icontains kwarg.
    """
    return Position.objects.filter(\
        company__icontains = company_s)

def user_username_wrapper(username_s):
    """
    Wraps the User.objects.filter
    method on username__icontains kwarg.
    """
    return User.objects.filter(\
        username__icontains = username_s)

def user_fullname_wrapper(fullname_s):
    """
    Wraps the User.objects.filter
    method on first_name__icontains
    and last_name__icontains kwargs.
    """
    name_l = fullname_s.split(' ')
    try:
        return User.objects.filter(\
            first_name__icontains = name_l[0],\
            last_name__icontains = name_l[1])        

    except IndexError:        
        return User.objects.filter(\
            Q(first_name__icontains = name_l[0]) |\
            Q(last_name__icontains = name_l[0]))

def get_titles(request):
    """
    Queries for positions starting with input 
    contained within GET request.
    """
    return get_generic_val(request,\
        position_title_wrapper,\
        'title') 

def get_companies(request):
    """
    Queries for company names starting 
    with input contained within GET request.
    """
    return get_generic_val(request,\
        position_company_wrapper,\
        'company') 

def get_usernames(request):
    """
    Queries for usernames starting with input
    contained within GET request.
    """
    return get_generic_val(request,\
        user_username_wrapper,\
        'username')        

def get_fullnames(request):
    """
    Queries for first/last names starting with input
    contained within GET request.
    """
    return get_generic_val(request,\
        user_fullname_wrapper,\
        'first_name',
        'last_name')        

coup/core/views.py
from django.shortcuts import render

# Create your views here.

coup/dashboard/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.db.models import Q
from django.contrib.auth.mixins import LoginRequiredMixin

from coup.positions.models import Position, Comment
from coup.users.models import User

LOGIN_URL = '/login/'

def recommend_user(self):
        
    
    rec_users = user_objects.filter(Q(faculty="Sciences")\
                                             | Q(program="Computing Science"))
    return rec_users
    
class DashBoardView(LoginRequiredMixin,\
                    ListView):
    """
    Generic view used to render the homepage aka
    dashboard of the website.
    """
    login_url = LOGIN_URL
    model = User
    template_name = "dashboard/index.html"

    def get_context_data(self, **kwargs):
        context = super(DashBoardView, self).get_context_data(**kwargs)
        #context['recent_list'] = Position.objects.exclude(\
         #                           user=self.request.user).order_by('-id')
        
        """user_objects = User.objects.exclude(id=self.request.user.id)
        rec_users = user_objects.filter(\
                                Q(faculty=self.request.user.faculty) | \
                                Q(program=self.request.user.program))

        context['recommend_users'] = rec_users"""
        return context


    

coup/templates/positions/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h2 id="profile-header">
        Your Positions
    </h2>

        <a class="profile-link header-link" 
            href="{% url 'positions:add-position' %}">
            Add New Position
        </a>
        <a  class="profile-link header-link" 
            href="{% url 'search:searchView' %}">
            Find Position
        </a>

        {% if request.user.is_authenticated %}
        <div class="description"> 
            <ul class="description-details">
            {% if position_list %}
                {% for position in position_list %}
                    <li class="detail position">
                        <a href="{{ position.get_absolute_url }}">
                            {{ position.title }} @ {{ position.company }}
                        </a>
                    </li>
                {% endfor %}
              </ul>

            {% else %}
                <li class="detail position">
                    <p>You currently have no added positions.</p>
                </li>
            {% endif %}
        </div>
        {% endif %}

    {% if recommended_list %}
    <h2 id="profile-header">
        Recommended
    </h2>
    {% endif %}
        {% for rec in recommended_list %}
            <div class="description">
                <ul class="description-details">
                    <li class="detail user">
                        <label>
                            User:
                        </label>
                        <a href="{% url 'users:view_profile' rec.user.slug %}">
                            {{ rec.user }}
                        </a>
                    </li>
                    <li class="detail company">
                        <label>
                            Company:
                        </label>
                        {{ rec.company }}     
                    </li>
                    <li class="detail title">
                        <label>
                            Title:
                        </label>
                        {{ rec.title }}
                    </li>
                    <li class="detail during">
                        <label>
                            During:
                        </label>
                        {{ rec.start_month }} {{ rec.start_year }}
                        {% if recent.end_year %}
                            - {{ recent.end_month }} {{ recent.end_year }}
                        {% endif %}
                    </li>
                    <li class="detail comment">
                        <label>
                            Description:
                        </label>
                        <div class="comment">
                            {{ rec.comment_set.get.comment }}
                        </div>
                    </li>
                    <li class="detail position-links">
                        <a id="update-position" class="profile-link"
                           href="{{ rec.get_absolute_url }}">
                            View
                        </a>
                    </li>
                </ul>
            </div>
        {% endfor %}
  
    
    <h2 id="profile-header">
        Recently Added
    </h2>

        {% for recent in recent_list %}
            <div class="description">
                <ul class="description-details">
                    <li class="detail user">
                        <label>
                            User:
                        </label>
                        <a href="{% url 'users:view_profile' recent.user.slug %}">
                            {{ recent.user }}
                        </a>
                    </li>
                    <li class="detail company">
                        <label>
                            Company:
                        </label>
                        {{ recent.company }}     
                    </li>
                    <li class="detail title">
                        <label>
                            Title:
                        </label>
                        {{ recent.title }}
                    </li>
                    <li class="detail during">
                        <label>
                            During:
                        </label>
                        {{ recent.start_month }} {{ recent.start_year }}
                        {% if recent.end_year %}
                            - {{ recent.end_month }} {{ recent.end_year }}
                        {% endif %}
                    </li>
                    <li class="detail comment">
                        <label>
                            Description:
                        </label>
                        <div class="comment">
                            {{ recent.comment_set.get.comment }}
                        </div>
                    </li>
                    <li class="detail position-links">
                        <a id="update-position" class="profile-link"
                           href="{{ recent.get_absolute_url }}">
                            View
                        </a>
                    </li>
                </ul>
            </div>
        {% endfor %}
                    
{% endblock %}

coup/templates/positions/position_add.html
{% extends "base_position.html" %}

{% block header %}
    <h2 id="profile-header">
        Add a New Position
    </h2>
{% endblock %}

coup/templates/positions/position_detail.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<h2 id="profile-header">
Position Details
</h2>

{% if request.user == position.user %}
    <a class="profile-link header-link"
        href="{% url 'positions:edit-position' pk=position.pk slug=position.slug %}">
        Update
    </a>
    <a class="profile-link header-link"
        href="{% url 'positions:delete-position' pk=position.pk slug=position.slug %}">
        Delete
    </a>
{% endif %}

<a class="profile-link header-link"
    href="{% url 'positions:index' %}">
    Back To Positions
</a>

<div class="description">
    <ul class="description-details">
        <li class="detail">
            <label>
                User:
            </label>
            <a href="{{ position.user.get_absolute_url }}">
                {{ position.user.username }}
            </a>
        </li>
        <li class="detail">
            <label>
                Company:
            </label>
            {{ position.company }}
        </li>
        <li class="detail">
            <label>
                Title:
            </label>
            {{ position.title }}
        </li>
        {% if position.location_addr %}
            <li class="detail">
                <label>
                    Location:
                </label>
                {{ position.location_addr }}
            </li>
        {% endif %}
        {% if position.start_year %}
            <li class="detail">
                <label>
                    Start Date:
                </label>
                {% if position.start_month %}
                    {{ position.start_month }} {{ position.start_year }}
                {% else %}
                    {{ position.start_year }}
                {% endif %}
            </li>
        {% endif %}
        {% if position.end_year %}
            <li class="detail">
                <label>
                    End Date:
                </label>
                {% if position.end_month %}
                    {{ position.end_month }} {{ position.end_year }}
                {% else %}
                    {{ position.end_year }}
                {% endif %}
            </li>
        {% endif %}
        {% if position.comment_set.get.comment %}
            <li class="detail">
                <label>
                    Description:
                </label>
                <div class="comment">
                    {{ position.comment_set.get.comment }}
                </div>
            </li>
        {% endif %}
    </ul> 
</div>

{% endblock %}

coup/templates/positions/position_edit.html
{% extends "base_position.html" %}

{% block header %}
    <h2 id="profile-header">
        Update Profile
    </h2>
{% endblock %}

coup/templates/positions/position_overview.html
{% extends "base_generic.html" %}

{% block content %}
    <h2 id="profile-header">
        Your Positions
    </h2>

        <a class="profile-link header-link" 
            href="{% url 'positions:add-position' %}">
            Add New Position
        </a>
        <a  class="profile-link header-link" 
            href="{% url 'search:searchView' %}">
            Find Position
        </a>

        {% if request.user.is_authenticated %}
        {% if position_list %}
            {% for position in object_list %}
            <div class="description">
                <ul class="description-details">
                    <li class="detail">
                        <label>
                            User:
                        </label>
                        <a href="{{ position.user.get_absolute_url }}">
                            {{ position.user.username }}
                        </a>
                    </li>
                    <li class="detail">
                        <label>
                            Company:
                        </label>
                        {{ position.company }}
                    </li>
                    <li class="detail">
                        <label>
                            Title:
                        </label>
                        {{ position.title }}
                    </li>
                    {% if position.location_addr %}
                        <li class="detail">
                            <label>
                                Location:
                            </label>
                            {{ position.location_addr }}
                        </li>
                    {% endif %}
                    {% if position.start_year %}
                        <li class="detail">
                            <label>
                                Start Date:
                            </label>
                            {% if position.start_month %}
                                {{ position.start_month }} {{ position.start_year }}
                            {% else %}
                                {{ position.start_year }}
                            {% endif %}
                        </li>
                    {% endif %}
                    {% if position.end_year %}
                        <li class="detail">
                            <label>
                                End Date:
                            </label>
                            {% if position.end_month %}
                                {{ position.end_month }} {{ position.end_year }}
                            {% else %}
                                {{ position.end_year }}
                            {% endif %}
                        </li>
                    {% endif %}
                    {% if position.comment_set.get.comment %}
                        <li class="detail">
                            <label>
                                Description:
                            </label>
                            <div class="comment">
                                {{ position.comment_set.get.comment }}
                            </div>
                        </li>
                    {% endif %}
                </ul> 
            </div>
            {% endfor %}

        {% else %}
            <li class="detail position">
                <p>You currently have no added positions.</p>
            </li>
        {% endif %}
    {% endif %}

     {% if is_paginated %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% else %}
                <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                <li>
                    <a href="?page={{ i }}">
                        {{ i }}
                    </a>
                </li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% else %}
                <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
        </ul>
    {% endif %}
   
{% endblock %}